name: Run rspec test suite

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongo:
        image: mongo
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Start Postgres
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Rspec
      run: bundle exec rake spec:all
